# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-10 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastCpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LastMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('hostid', models.CharField(max_length=500, null=True)),
                ('ip', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('firewall', models.CharField(max_length=500, null=True)),
                ('mcafee', models.CharField(max_length=500, null=True)),
                ('maxusedmemory', models.CharField(max_length=500, null=True)),
                ('maxusedcpu', models.CharField(max_length=500, null=True)),
                ('freediskc', models.CharField(max_length=500, null=True)),
                ('freediskd', models.CharField(max_length=500, null=True)),
                ('freediske', models.CharField(max_length=500, null=True)),
                ('freediskf', models.CharField(max_length=500, null=True)),
                ('freediskg', models.CharField(max_length=500, null=True)),
                ('freediskh', models.CharField(max_length=500, null=True)),
                ('freediski', models.CharField(max_length=500, null=True)),
                ('telnet', models.CharField(max_length=500, null=True)),
                ('ssl_cert_exp', models.CharField(max_length=500, null=True)),
                ('win_active', models.CharField(max_length=500, null=True)),
                ('critc_sys_log', models.CharField(max_length=500, null=True)),
                ('sql_login_user', models.CharField(max_length=500, null=True)),
                ('sql_xp_cmdshell', models.CharField(max_length=500, null=True)),
                ('sql_version', models.CharField(max_length=500, null=True)),
                ('sql_file_size', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lastmemory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='zbxapp.Server'),
        ),
        migrations.AddField(
            model_name='lastcpu',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='zbxapp.Server'),
        ),
    ]
