# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-29 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastCpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.FloatField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LastMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.FloatField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('firewall', models.CharField(max_length=500, null=True)),
                ('mcafee', models.CharField(max_length=500, null=True)),
                ('freedisk', models.CharField(max_length=500, null=True)),
                ('telnet', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lastmemory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoryhist', to='zbxapp.Server'),
        ),
        migrations.AddField(
            model_name='lastcpu',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpuhist', to='zbxapp.Server'),
        ),
    ]
