# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zbxapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='freedisk',
            new_name='freediskc',
        ),
        migrations.AddField(
            model_name='server',
            name='freediskd',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='freediske',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='freediskf',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='freediskg',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='lastcpu',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cpu', to='zbxapp.Server'),
        ),
        migrations.AlterField(
            model_name='lastmemory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory', to='zbxapp.Server'),
        ),
    ]
