# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxapp', '0002_auto_20180430_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='freediskh',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='freediski',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
