# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxapp', '0004_server_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastcpu',
            name='cpu',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='lastmemory',
            name='memory',
            field=models.CharField(max_length=500),
        ),
    ]
