# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zbxapp', '0005_auto_20180430_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='maxusedcpu',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='maxusedmemory',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
